### ISSUE TITLE
OCAP refusing to start and be found ingame when loaded.

### ISSUE THREAD

**Issue by SGTdanny50567** [OCAP2/OCAP#1]
**OCAP Version:** `v3.3.0`
**Server OS:** `Windows`

**Description:**
We recently moved to a new server box which also included a change of IP, as a consequnce I updated the OCAP mod folder, the webserver folder and the userconfig to match the new IP's. Upon lauching of the server to test the feature on the new box, the RPT says that;

```Call extension 'OcapReplaySaver2' could not be loaded: The specified module could not be found.``` 

I've updated the mod, redone all the IP's, secret passwords and tested in game and it doesn't work. It's not even outputting the logs speciffically for ocap itself into its own folders.

**Steps to reproduce:**
Server specific, worked on the last box not on this one.

**RPT File**

RPT file uploaded to Google Drive
[RPT File](https://drive.google.com/file/d/1gLwQMRWU-4nIS8F4VgiHjYvOL8NVcBmL/view?usp=sharing)

**Comment by Zealot111** [comment]
@SGTdanny50567 try in options.json setup server on all interfaces as "0.0.0.0:80" , check again firewall rules. try open ocap in browser typing 192.168.0.1 or localhost. attach your configuration files (you may omit passwords though)
