### ISSUE TITLE
export data on mission end

### ISSUE THREAD

**Issue by Fank** [OCAP2/OCAP#10]
When the [MPEnded](https://community.bistudio.com/wiki/Arma_3:_Mission_Event_Handlers#MPEnded) is triggered the data should be exported, this should be optional.
Also required for this is some kind of default "text" or tag which is exported by default.

**Comment by indig0fox** [comment]
This is already present via `ocap_saveMissionEnded` in userconfig. It provides a default string of "Mission ended automatically" with no side won indication.

https://github.com/OCAP2/addon/blob/8a62baef4e72197ef8dc03cf1493be6660f2e1ba/addons/%40ocap/addons/ocap/functions/fn_addEventMission.sqf#L27-L31

https://github.com/OCAP2/addon/blob/8a62baef4e72197ef8dc03cf1493be6660f2e1ba/userconfig/ocap/config.hpp#L6

**Comment by Fank** [comment]
Did you changed something recently on it?
Because this didn't worked for us.

**Comment by indig0fox** [comment]
We might need to check the exact extension parameters, how it's being parsed/what it expects from the addon.

**Comment by Fank** [comment]
nvm we called `BIS_fnc_endMission` not `BIS_fnc_endMissionServer`
