### ISSUE TITLE
UI drop-down to control marker visibility / declutter

### ISSUE THREAD

**Issue by indig0fox** [OCAP2/OCAP#30]
Options
- Show Markers and Captions
- Show Markers
- Hide Markers

hide popups (text) in option 2
hide popups and all markers (.hide()?) in option 3

Always show projectiles but if option 3 selected, hide popup (text) of projectile markers.

All projectile marker types are mil_triangle, red color and Global, or are icon from magicons path.

**Comment by Fank** [comment]
What do you think about something more userfriendly, which has the ability to allow more visibility changes later:
![image](https://user-images.githubusercontent.com/1900106/126031329-8dbb4ace-b4a9-45ec-b151-ff3d5ce76384.png)

**Comment by Fank** [comment]
Like show caption for:
- marker
- unit
- vehicles
- ammo/rockets/shells

**Comment by indig0fox** [comment]
- markers
- marker names
- unit names
- vehicle labels
- projectile labels
- projectiles

**Comment by Fank** [comment]
Is this here some kind of duplicate? #26

**Comment by indig0fox** [comment]
Yes, the items in the other issue are a duplicate of what's here

**Comment by indig0fox** [comment]
Partial duplicate of https://github.com/OCAP2/OCAP/issues/26
Some visibility control implemented with Leaflet control for 2.0
