### ISSUE TITLE
Add roleDescription prefix to show the slot a player has taken

### ISSUE THREAD

**Issue by Fank** [OCAP2/OCAP#4]
Current:
![image](https://user-images.githubusercontent.com/1900106/125118645-4a677880-e0f0-11eb-923e-ebc4d98bdfa2.png)

In mission:
![image](https://user-images.githubusercontent.com/1900106/125118640-46d3f180-e0f0-11eb-8531-5a18eba2ad0c.png)

**Comment by indig0fox** [comment]
Need web implementation of Entity:Unit to, if role provided in JSON, split at '@' and prepend index 0 in parentheses before player name in the left panel
