### ISSUE TITLE
UpdateUnit optimization

### ISSUE THREAD

**Issue by Zealot111** [OCAP2/OCAP#48]
it is also worth to optimize UpdateUnit because unit name also spammed across all frame updates and could be long 10 symbols or longer,for example if unit name = "" we can use unit name from previous frames (or just create separate unitName parameter in unit object)

**Comment by indig0fox** [comment]
Present in [62affe441bd736e10fece115c4da2aee6c302ee5](https://github.com/OCAP2/addon/commit/62affe441bd736e10fece115c4da2aee6c302ee5)
