### ISSUE TITLE
ACE Refuel Helper

### ISSUE THREAD

**Issue by fank** [OCAP2/OCAP#49]
Are shown as helicopter
![image](https://user-images.githubusercontent.com/1900106/127750873-9a6a759c-3505-47aa-b44c-9f2e6746d8d5.png)

**Comment by indig0fox** [comment]
ACE3 feature:
1. create a fuel source from an existing object using `[cursorObject, 100] call ace_refuel_fnc_makeSource`
2. ACE interact with the object and Take Fuel Nozzle
3. A Refuel Helper object is created on the source object as you drag the nozzle around, attached by a hose

`ace_refuel_helper` inherits from Helicopter_Base_F but has an invisible model (`\A3\Weapons_f\empty`)
There are other logic-style items that do this, such as the fast-rope insertion system on the RHS UH-1Y helicopter.

Added exclusion
```sqf
if (getText(configFile >> "CfgVehicles" >> _this >> "model") isEqualTo "\A3\Weapons_f\empty") exitWith {"unknown"};
```
