### ISSUE TITLE
CUP SearchLight is shown as an "?"

### ISSUE THREAD

**Issue by Fuggschen** [OCAP2/OCAP#52]
Here is the classname that is shown as an "?":

CUP Mod:
* CUP_B_SearchLight_static_ACR

We are also using a Mod called "BoxLoader - Vehicle in Vehicle loading" and it creates a empty Vehicle for the Boxes to attach to. Those shouldn't be visible in the recording at all (maybe adding a classname blacklist would be helpful):
* Land_Boxloader_* (sometimes lowercase)

**Comment by indig0fox** [comment]
Re: your second ask, both classname and KindOf blacklist options exist in the userconfig/config.hpp file. Simply add the baseclass to `ocap_excludeKindFromRecord`, or the direct classes to the `ocap_excludeClassFromRecord` array.

**Comment by Fuggschen** [comment]
> Re: your second ask, both classname and KindOf blacklist options exist in the userconfig/config.hpp file. Simply add the baseclass to `ocap_excludeKindFromRecord`, or the direct classes to the `ocap_excludeClassFromRecord` array.

Okay thanks for the Info. Didn't saw this feature. Can I use an asterix to cover multiple classes or should I find the baseclass?

**Comment by fank** [comment]
The matches checks against classes, not strings, so you need to find the base class.
https://github.com/OCAP2/addon/blob/1bf329a6840e12fa28218a83daaced27bc1fddbf/addons/%40ocap/addons/ocap/functions/fn_startCaptureLoop.sqf#L173
