### ISSUE TITLE
Performance issue due to ACE GPS Markers

### ISSUE THREAD

**Issue by GoldJohnKing** [OCAP2/OCAP#56]
I'm running a 2 hours zeus mission with OCAP.

OCAP records those ACE GPS Markers (player markers), which causes huge amount of marker recorded and becomes huge performance issues during playback.

I ask for a feature to exclude those markers if possible. If not, I would like to have a function that can completely disable marker recording.

Thanks for your effort on this splendid project!

**Comment by indig0fox** [comment]
This setting will allow you to specify an array of marker prefixes to be excluded from recording. You can use the `allMapMarkers` command to see what markers are present in a mission -- I recommend loading up a mission, seeing what prefixes are in use, and adding any exclusions you wish to your userconfig file shown below.
https://github.com/OCAP2/addon/blob/9d41a9cbe7cf54ea5c5c0c76cf8ae95b34c1c570/userconfig/ocap/config.hpp#L8
