### ISSUE TITLE
Markers created during init are not excluded by ocap_excludeMarkerFromRecord

### ISSUE THREAD

**Issue by Superxpdude** [OCAP2/OCAP#57]
While markers created during the mission that match one of the strings in `ocap_excludeMarkerFromRecord` are properly excluded from the capture, this same check is not applied to markers that are created in the editor, or during `preInit`/`postInit`.

These markers don't get updated at all as the mission progresses, so they will remain in OCAP with their original text and positions throughout the entire recording.

As far as I can tell, I think this is because the "Initial marker check" in [fn_handleMarkers.sqf](https://github.com/OCAP2/addon/blob/1bf329a6840e12fa28218a83daaced27bc1fddbf/addons/%40ocap/addons/ocap/functions/fn_handleMarkers.sqf#L261-L288) doesn't have the same "exclusion" check that the `MarkerCreated`, `MarkerUpdated`, and `MarkerDeleted` checks do.

**Comment by indig0fox** [comment]
This will be fixed in 2.0.0 addon 👍

**Comment by indig0fox** [comment]
handled in https://github.com/OCAP2/addon/commit/e55ac6d5b4d8e78c2fed61d8acd36ddf7df81fa6
