### ISSUE TITLE
add new map "Vis"

### ISSUE THREAD

**Issue by goguryeo1** [OCAP2/OCAP#58]
```
{
	"name": "Vis",
	"worldName": "Vis",
	"worldSize": 20480,
	"imageSize": 16384,
	"multiplier": 0.8,
	"maxZoom": 7
}
```
https://drive.google.com/file/d/1iW3QtIgbUNs6OpYGUBbcJoQPZDzVL8xM/view?usp=sharing

https://steamcommunity.com/sharedfiles/filedetails/?id=1120714022

Thank you for your works.

**Comment by indig0fox** [comment]
Added to topographic-only in the Google Drive folder, thank you
