### ISSUE TITLE
FOW Kokoda Track map is off-scale

### ISSUE THREAD

**Issue by VyMajoris** [OCAP2/OCAP#63]
![image](https://user-images.githubusercontent.com/4342296/163740776-9e6eaa14-8f95-40db-b4f8-60dbcebc61ca.png)
http://aar.globalconflicts.net/?file=2022_04_17__23_08_CO27BattleofKokoda1.json&frame=223&zoom=0&x=4.759277343750001&y=17.923828125000004

From this mod:
https://steamcommunity.com/workshop/filedetails/?id=891433622

**Comment by indig0fox** [comment]
The worlds
fow_map_hendersion
fow_map_tarawa
swu_kokoda_map
have been rendered with the latest terrain views available. Each has been made available to stream from the cloud tile server as well as from Google Drive in the `OCAP Maps\Render2.0` directory. I've double checked your linked recording and units are positions more accurately, with the red circle in the NW corner of the map.

Thank you for reporting and supporting our development!
