### ISSUE TITLE
Script errors in recorder.pbo from Discord

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#64]
```sqf
13:48:57 Error in expression <
call OCAP2_recorder_fnc_startRecording
["OCAP2_customEvent", ["generalEvent", ">
13:48:57   Error position: <["OCAP2_customEvent", ["generalEvent", ">
13:48:57   Error Missing ;
13:48:57 File x\OCAP2\addons\recorder\fnc_init.sqf..., line 121
13:48:57 Error in expression <
call OCAP2_recorder_fnc_startRecording
["OCAP2_customEvent", ["generalEvent", ">
13:48:57   Error position: <["OCAP2_customEvent", ["generalEvent", ">
13:48:57   Error Missing ;
13:48:57 File x\OCAP2\addons\recorder\fnc_init.sqf..., line 121
13:48:57 Error in expression <edIn && !(_object getVariable [QGVARMAIN(hasAdminControls), true])) then {

[_id>
13:48:57   Error position: <(hasAdminControls), true])) then {

[_id>
13:48:57   Error Missing ]
13:48:57 File x\OCAP2\addons\recorder\fnc_eh_onUserAdminStateChanged.sqf..., line 5
13:48:57 Error in expression <edIn && !(_object getVariable [QGVARMAIN(hasAdminControls), true])) then {

[_id>
13:48:57   Error position: <(hasAdminControls), true])) then {

[_id>
13:48:57   Error Missing ]
13:48:57 File x\OCAP2\addons\recorder\fnc_eh_onUserAdminStateChanged.sqf..., line 5
13:48:57 Error in expression < missionNamespace getVariable [QGVARMAIN(administratorList), nil];

if (isNil "_>
13:48:57   Error position: <(administratorList), nil];

if (isNil "_>
13:48:57   Error Missing ]
13:48:57 File x\OCAP2\addons\recorder\fnc_adminUIcontrol.sqf..., line 8
13:48:57 Error in expression < missionNamespace getVariable [QGVARMAIN(administratorList), nil];

if (isNil "_>
13:48:57   Error position: <(administratorList), nil];

if (isNil "_>
13:48:57   Error Missing ]
13:48:57 File x\OCAP2\addons\recorder\fnc_adminUIcontrol.sqf..., line 8
```
happens with this recorder.pbo
https://discord.com/channels/858402673066115102/871034165271855125/966763483720978432

does not happen with RC2.

**Comment by jonpas** [comment]
Line numbers in RPT errors are wrong, because `#include "script_component.hpp"` is not on top of the file. If you put it on top (above the header comment), you will get correct error (can check ACE3 how it looks).

> File x\OCAP2\addons\recorder\fnc_init.sqf..., line 121

This actual error is on line 143, missing `;`: https://github.com/OCAP2/addon/blob/e397415de51b069ef89142150b0b019eaa70148b/x/ocap2/addons/recorder/fnc_init.sqf#L143

> File x\OCAP2\addons\recorder\fnc_eh_onUserAdminStateChanged.sqf..., line 5

This is just missing `#include "script_component.hpp"` as a whole, so `QGVARMAIN` can't be expanded.

> File x\OCAP2\addons\recorder\fnc_adminUIcontrol.sqf..., line 8

Same here.

**Comment by MildlyInterested** [comment]
https://github.com/OCAP2/addon/blob/e397415de51b069ef89142150b0b019eaa70148b/x/ocap2/addons/recorder/fnc_init.sqf#L143
That one I actually found myself! But I don't know how to pack PBOs for mods so just reporting it here :)
