### ISSUE TITLE
[RC2] minMissionTime conditional wrong multiplier

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#65]
Your JSON reports 36 frames
This is the conditional that exits the exportData call early if that threshold is not met AND override param isn't fed, i.e. autosave and not using the CBA event
```sqf
_frameTimeDuration = (GVAR(frameCaptureDelay) * GVAR(captureFrameNo)) * 60;
if (_frameTimeDuration < GVAR(minMissionTime) && !_overrideLimits) exitWith {
```

**Comment by indig0fox** [comment]
Fix is in d6549e44bb245091375e2a7f9920423ce4412e28
