### ISSUE TITLE
[RC2] mininum Player check counting HCs

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#66]
from Discord chat:
> and BIS_fnc_listPlayers will exclude HC from the saveOnEmpty check. so both should be good

**Comment by jonpas** [comment]
Wasn't this fixed here https://github.com/OCAP2/addon/commit/286774e0e7f2d258016cb9ab7b440195eed8a7c6? No clue if that's in RC2 or not though.

**Comment by MildlyInterested** [comment]
I reported it two days after RC2 release and Indigo PMed me a fixed pbo so it probably got fixed in some branch. Just reporting it for completeness sake because I'm not sure whats known and what isn't.

**Comment by indig0fox** [comment]
Accounted for in above commit, post RC2 release.
