### ISSUE TITLE
[RC2] Upload fails with 127.0.0.1:5000, works with localhost:5000

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#67]
have not reproduced it yet on a different system

**Comment by L00Cyph3r** [comment]
Sounds to me like the server was maybe not listening on 127.0.0.1, could be that it was only listening on the IPv6 version of that, can you check what address it’s listening on once you start the webserver?
`netstat -n`

**Comment by MildlyInterested** [comment]
Tried reproducing it on a second server, did not occur. Closing.
