### ISSUE TITLE
[Web] Feature: Show playernames while in vehicle

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#69]
Currently no playernames are shown. 
Showing all occupants might be a bit much but having the vehicle commanders name visible would be nice.

**Comment by indig0fox** [comment]
Can this be reproed in 2.0.0 RC2?

**Comment by MildlyInterested** [comment]
Still the case in RC2 with the "hide AI names" js modification. See here http://connect.16aa.net:5000/?file=2022_09_26__00_29_BarkhaneIV.json&frame=3638&zoom=5&x=-229.15497306730808&y=152.56674682884565

**Comment by indig0fox** [comment]
Resolved in https://github.com/OCAP2/web/commit/419509510c5b2659dd752d7323c9c690d9c4ad09
