### ISSUE TITLE
[RC2] Flares not disappearing in playback

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#70]
1. Helicopter pops flares
2. Playback shows them
3. They do not disappear

**Comment by MildlyInterested** [comment]
Has been fixed by the recorder.pbo posted in discord but that one contains syntax errors and can't be tested.
Discord link to pbo: https://discord.com/channels/858402673066115102/871034165271855125/966763483720978432

**Comment by indig0fox** [comment]
Accounted for in [e397415de51b069ef89142150b0b019eaa70148b](https://github.com/OCAP2/addon/pull/29/commits/e397415de51b069ef89142150b0b019eaa70148b) by adding ShotCM ammo class.
