### ISSUE TITLE
Show mission-/in game & real life time

### ISSUE THREAD

**Issue by Fank** [OCAP2/OCAP#8]
The mission time & real life time should be shown.

Markers shows timestamp, but because i can't see the time i have no clue if they are old or new
![image](https://user-images.githubusercontent.com/1900106/124643443-63262300-de91-11eb-9ed5-c0c1ffc3926c.png)

**Comment by Zealot111** [comment]
we could add additional real world time and game time as parameters when starting mission. Since all frame times usually the same, we can easily calculate actual time when marker placed/changed. (if time scale is 1:1 on mission, this is most common variant)
